# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serve < Formula
  desc "Lightweight self-hosted tunnel to expose local dev servers publicly"
  homepage "https://github.com/swyftlabs/serve"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/swyftlabs/serve/releases/download/v0.2.1/serve_0.2.1_darwin_amd64.tar.gz"
      sha256 "616025a2cd04391fcf0016e84b296f2c0fc168a70ec371ab9e352c46617a4fef"

      define_method(:install) do
        bin.install "serve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/swyftlabs/serve/releases/download/v0.2.1/serve_0.2.1_darwin_arm64.tar.gz"
      sha256 "88c46af4701ee8e5c159c6c59d0042a5cdca566c36c3115753090f8b5c22d19d"

      define_method(:install) do
        bin.install "serve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swyftlabs/serve/releases/download/v0.2.1/serve_0.2.1_linux_amd64.tar.gz"
      sha256 "01f44ccc41f9a590641c067989af2b0cde606ce993f3aed157ae341569773681"
      define_method(:install) do
        bin.install "serve"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swyftlabs/serve/releases/download/v0.2.1/serve_0.2.1_linux_arm64.tar.gz"
      sha256 "b45bb174c8af81f303964a0f75f483cffa4224b27349cb34dc9b3ed7e056e598"
      define_method(:install) do
        bin.install "serve"
      end
    end
  end
end
