# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serve < Formula
  desc "Public tunnel for hosted serve accounts"
  homepage "https://github.com/swyftlabs/serve"
  version "0.5.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/swyftlabs/serve-dist/releases/download/v0.5.1/serve_0.5.1_darwin_amd64.tar.gz"
      sha256 "cefff7e91129a93ac06c782f00cc90fe93208f613fc1074537fc064dc8b89786"

      define_method(:install) do
        bin.install "serve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/swyftlabs/serve-dist/releases/download/v0.5.1/serve_0.5.1_darwin_arm64.tar.gz"
      sha256 "275891e6ba7bdf9118b342661643ef6ec0685f7f04c8f2a30256bb2ebe183ed9"

      define_method(:install) do
        bin.install "serve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swyftlabs/serve-dist/releases/download/v0.5.1/serve_0.5.1_linux_amd64.tar.gz"
      sha256 "2ddf7d01fbfcada63c911a3fcce922025b83daf19c4e6b7a0ae7a07dcb1b3cfc"
      define_method(:install) do
        bin.install "serve"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swyftlabs/serve-dist/releases/download/v0.5.1/serve_0.5.1_linux_arm64.tar.gz"
      sha256 "6814cf00ed0e2b18d1af02b97b8b061eb4c0e4831cd6dddb9efb886a155161da"
      define_method(:install) do
        bin.install "serve"
      end
    end
  end
end
