# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser for swyftlabs/serve v0.2.
class Serve < Formula
  desc "Lightweight self-hosted tunnel to expose local dev servers publicly"
  homepage "https://github.com/swyftlabs/serve"
  version "0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/swyftlabs/serve/releases/download/v0.2/serve_0.2_darwin_arm64.tar.gz"
      sha256 "2ebe8aca3a0bd2bf485cd8b7c30db6f6044ddb7ad409e25f56d0ae02e1d90220"

      def install
        bin.install "serve"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/swyftlabs/serve/releases/download/v0.2/serve_0.2_darwin_amd64.tar.gz"
      sha256 "236e0e8b6ebc49a5f26c7492fd65b8d61e61dd5469ede048c31664680af2b9b2"

      def install
        bin.install "serve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swyftlabs/serve/releases/download/v0.2/serve_0.2_linux_arm64.tar.gz"
      sha256 "6a3662bcc9322bf56e37cd5f06e2a76c5b2e017c40dbad312644ec7279cee0aa"

      def install
        bin.install "serve"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/swyftlabs/serve/releases/download/v0.2/serve_0.2_linux_amd64.tar.gz"
      sha256 "03927c6943b5c6230493ea3610c23747171e4cb0caecc59756bff672907c837a"

      def install
        bin.install "serve"
      end
    end
  end

  test do
    system "#{bin}/serve", "--version"
  end
end
